Repository jenkins-infra/packer-images, pull requests merged in 2022-07, with the labels that each got.

#268 Revert "hotfix(windows-2019) pin to 2022 05 11 build on AWS "
  datasources.pkr.hcl
Labels: skip-changelog

#269 feat: add asdf 0.10.2 (linux) and ruby 2.6.10 (linux, windows)
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/updatecli.d/asdf.yml
Labels: enhancement

#272 fix(linux) correct installations of asdf and ruby for user `jenkins`
  provisioning/ubuntu-provision.sh
Labels: bug

#277 feat: add yq on all platforms
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: enhancement

#290 fix: remoting manifest
  updatecli/updatecli.d/jenkins-remoting.yml
Labels: chore
