Repository jenkins-infra/packer-images, pull requests merged in 2022-11, with the labels that each got.

#398 feat: add updatecli
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: enhancement

#395 chore: pin docker version for Linux and track it with updatecli
  Jenkinsfile_k8s
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  updatecli/scripts/fetch-docker-ce-latest-version.sh
  updatecli/scripts/run-in-docker.sh
  updatecli/updatecli.d/docker-ce.yaml
Labels: chore, docker-ce

#397 chore(updatecli) track chromium version
  provisioning/ubuntu-provision.sh
  updatecli/scripts/fetch-chromium-latest-version.sh
  updatecli/updatecli.d/chromium.yml
Labels: chore

#402 feat: add awscli v2.8.9
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: enhancement, awscli

#404 feat: add netlify-deploy 0.1.4
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: enhancement, netlify-deploy

#405 chore(updatecli) track versions of updatecli, awscli and netlify-deploy
  updatecli/updatecli.d/awscli.yml
  updatecli/updatecli.d/netlify-deploy.yml
  updatecli/updatecli.d/updatecli.yml
Labels: chore, awscli, netlify-deploy, updatecli

#410 fix(windows) pin powershell-core version (pwsh) to 7.2.7
  provisioning/tools-versions.yml
  provisioning/windows-provision.ps1
Labels: bug, windows

#412 chore(updatecli): add a manifest to bump pwsh
  updatecli/updatecli.d/pwsh.yml
Labels: chore

#411 feat: add terraform v1.1.9
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: enhancement

#413 feat: add kubectl 1.23.13
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/updatecli.d/pwsh.yml
Labels: enhancement

#417 chore: stop tracking chromium version and always install the latest version available
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/scripts/fetch-chromium-latest-version.sh
  updatecli/updatecli.d/chromium.yml
Labels: chore

#425 feat: add JDK19 version `19.0.1+10`
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/scripts/check-jdk.sh
  updatecli/updatecli.d/jdk19.yml
Labels: enhancement
