Repository jenkins-infra/packer-images, pull requests merged in 2022-06, with the labels that each got.

#254 hotfix(windows-2019) pin to 2022 05 11 build on AWS
  datasources.pkr.hcl
Labels: bug

#257 feat: make packer-images the source of truth for Maven version
  Jenkinsfile_k8s
  updatecli/updatecli.d/maven.yml
Labels: ci-skip, skip-ci

#260 fix(Windows): ensure both Windows Powershell and Powershell Core are available
  Jenkinsfile_k8s
  provisioning/tools-versions.yml
  provisioning/windows-provision.ps1
Labels: enhancement
