Repository jenkins-infra/packer-images, pull requests merged in 2023-10, with the labels that each got.

#835 cleanup(jdk19): remove jdk19
  goss/goss.yaml
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/updatecli.d/jdk19.yml
Labels: cleanup

#836 tests: check for `asdf` and `npm` with goss
  build-jenkins-agent-ubuntu.pkr.hcl
  goss/goss.yaml
  provisioning/ubuntu-provision.sh
  updatecli/updatecli.d/asdf.yml
Labels: chore, tests

#839 chore(updatecli): track the official jdk21 version instead of earlyavailable
  updatecli/scripts/check-jdk.sh
  updatecli/updatecli.d/jdk21.yml
Labels: chore

#850 fix(windows) bump pwsh back to `7.3.7`
  provisioning/tools-versions.yml
Labels: bug, windows, pwsh

#861 tests: fix failing NPM check by replacing it with a NodeJS check instead
  goss/goss.yaml
Labels: nodejs, tests

#860 feat: Bump JDK21 to Temurin 21+35 LTS version
  goss/goss.yaml
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: enhancement

#864 feat: add NodeJS to windows and track its version
  provisioning/windows-provision.ps1
  updatecli/updatecli.d/nodejs.yml
Labels: enhancement, updatecli, windows, nodejs

#868 hotfix(linux) revert remoting to `3174.v2c9e67f8f9df `
  provisioning/tools-versions.yml
Labels: bug

#818 tests(windows) Use `goss` for sanity checks for JDKs and trivy
  build-jenkins-agent-windows.pkr.hcl
  goss/goss-windows.yaml
  provisioning/windows-provision.ps1
Labels: chore, windows, goss, tests

#873 tests(windows) fix JDK8 goss check
  goss/goss-windows.yaml
Labels: tests

#801 fix(provision): clean playwright artifacts during sanity check
  goss/goss.yaml
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  updatecli/updatecli.d/playwright.yml
Labels: bug, hacktoberfest, hacktoberfest-accepted, playwright

#883 chore(updatecli) fix manifests when they need to updated both GOSS test harnesses
  updatecli/updatecli.d/jdk11.yml
  updatecli/updatecli.d/jdk17.yml
  updatecli/updatecli.d/jdk21.yml
  updatecli/updatecli.d/jdk8.yml
  updatecli/updatecli.d/playwright.yml
  updatecli/updatecli.d/trivy.yaml
Labels: chore, updatecli, jdk21, trivy, jdk8, jdk11, jdk17
