Repository jenkins-infra/packer-images, pull requests merged in 2023-12, with the labels that each got.

#922 chore(goss): move windows sanity checks from provider script to goss
  build-jenkins-agent-windows.pkr.hcl
  goss/goss-windows.yaml
  provisioning/windows-provision.ps1
Labels: chore, windows, goss, tests

#952 hotfix(goss) bump git LFS to 3.4.1
  goss/goss-linux.yaml
Labels: skip-changelog

#951 hotfix(updatecli): rename file within comment
  updatecli/updatecli.d/asdf.yml
  updatecli/updatecli.d/awscli.yml
  updatecli/updatecli.d/azcopy.yaml
  updatecli/updatecli.d/azure-cli.yml
  updatecli/updatecli.d/chocolatey.yml
  updatecli/updatecli.d/container-structure-test.yml
  updatecli/updatecli.d/docker-ce.yaml
  updatecli/updatecli.d/github-cli.yml
  updatecli/updatecli.d/hadolint.yml
  updatecli/updatecli.d/jenkins-remoting.yml
  updatecli/updatecli.d/jq.yml
  updatecli/updatecli.d/jx-release-version.yml
  updatecli/updatecli.d/launchable.yml
  updatecli/updatecli.d/netlify-deploy.yml
  updatecli/updatecli.d/packer.yml
  updatecli/updatecli.d/playwright.yml
  updatecli/updatecli.d/python3.yml
  updatecli/updatecli.d/trivy.yaml
  updatecli/updatecli.d/updatecli.yml
  updatecli/updatecli.d/vagrant.yml
Labels: skip-changelog

#949 feat(doctl): add doctl install on linux only
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
Labels: enhancement, doctl

#950 chore(updatecli/goss): include `doctl`
  goss/goss-linux.yaml
  updatecli/updatecli.d/doctl.yaml
Labels: chore, doctl

#957 fixup(goss): putting back exit-status: 0 which is required
  goss/goss-linux.yaml
  goss/goss-windows.yaml
Labels: goss, tests

#958 feat(xq) adding xq as new tool
  goss/goss-linux.yaml
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
Labels: enhancement, xq

#965 fix(yq) downgrade to 4.25.3
  goss/goss-linux.yaml
  goss/goss-windows.yaml
  provisioning/tools-versions.yml
  updatecli/updatecli.d/yq.yml
Labels: skip-changelog, yq
