Repository jenkins-infra/packer-images, pull requests merged in 2023-04, with the labels that each got.

#299 breaking: bump from Ubuntu 20.04 to Ubuntu 22.04
  Jenkinsfile_k8s
  build-jenkins-agent-ubuntu.pkr.hcl
  datasources.pkr.hcl
  goss/goss.yaml
  provisioning/ubuntu-provision.sh
Labels: breaking, ubuntu

#577 chore: disable concurrent builds on pull requests
  Jenkinsfile_k8s
Labels: chore

#571 feat(windows) ensure Docker-CE installation is pinned
  build-jenkins-agent-windows.pkr.hcl
  datasources.pkr.hcl
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/updatecli.d/docker-ce.yaml
Labels: enhancement, docker-ce, windows, ubuntu

#590 chore(cleanup AWS images) ensure staging images older than 7 days are removed
  Jenkinsfile_k8s
  cleanup/aws_images.sh
Labels: skip-changelog

#594 chore(cleanup AWS images) remove AMI with build_type=prod older than 2 months
  Jenkinsfile_k8s
Labels: skip-changelog

#595 chore(cleanup AWS snapshots) decrease threshold to 2 month
  cleanup/aws_snapshots.sh
Labels: skip-changelog

#596 cleanup: stop building EC2 Linux amd64 and EC2 Windows
  Jenkinsfile_k8s
Labels: cleanup

#591 Bump terraform to `1.4.4`
  provisioning/tools-versions.yml
Labels: enhancement, terraform

#597 chore(cleanup AWS snapshots) try to delete when older than 1 day
  cleanup/aws_snapshots.sh
Labels: skip-changelog

#598 chore: ensure that spot instances are used for packer builds
  build-jenkins-agent-ubuntu.pkr.hcl
  build-jenkins-agent-windows.pkr.hcl
  locals.pkr.hcl
  sources.pkr.hcl
Labels: skip-changelog

#575 feat(azure/arm64): add an arm64 ubuntu 22.04 image in azure ARM
  Jenkinsfile_k8s
  build-jenkins-agent-ubuntu.pkr.hcl
  locals.pkr.hcl
  sources.pkr.hcl
Labels: enhancement, ubuntu, azure, arm64

#607 Revert "feat(azure/arm): enable arm64 azure build"
  Jenkinsfile_k8s
  build-jenkins-agent-ubuntu.pkr.hcl
  locals.pkr.hcl
  sources.pkr.hcl
Labels: skip-changelog

#612 chore(updatecli) fix python manifest
  updatecli/updatecli.d/python3.yml
Labels: skip-changelog

#627 fix(cleanup/azure): remove unrecognized `--yes --no-wait` parameters for `az sig` command
  cleanup/azure.sh
Labels: skip-changelog

#629 chore(cleanup Azure) parallelize the Gallery version deletion and fix shellcheck issues
  cleanup/azure.sh
Labels: skip-changelog

#634 fix(ubuntu) correct GPG public key for datadog
  provisioning/ubuntu-provision.sh
Labels: bug

#635 chore(azure cleanup) split gallery image and instance cleanup + use time threshold for gallery images
  Jenkinsfile_k8s
  cleanup/aws_images.sh
  cleanup/azure.sh
  cleanup/azure_gallery_images.sh
Labels: skip-changelog

#636 chore(azure cleanup) remove resources from the packer-builds RGs
  Jenkinsfile_k8s
  cleanup/azure.sh
Labels: skip-changelog
