Repository jenkins-infra/packer-images, pull requests merged in 2023-09, with the labels that each got.

#792 Bump `nodejs` version to 18.17.0
  provisioning/tools-versions.yml
Labels: enhancement, nodejs

#791 chore: switch temuring JDK21 from "nighlty builds" to `ea` (weekly builds) line to allow version tracking
  goss/goss.yaml
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/scripts/check-jdk.sh
Labels: chore

#810 Revert "Bump launchable version to 1.75.0" (to version 1.66.0)
  provisioning/tools-versions.yml
Labels: bug, launchable

#815 feat: add trivy `0.45.1`
  build-jenkins-agent-ubuntu.pkr.hcl
  goss/goss.yaml
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
  updatecli/updatecli.d/trivy.yaml
Labels: enhancement, trivy

#820 chore(updatecli): add a manifest to track goss
  updatecli/updatecli.d/goss.yml
Labels: chore, updatecli, goss

#821 chore(ubuntu): rework of the goss file
  goss/goss.yaml
Labels: chore, ubuntu

#826 hotfix(ubuntu) correct azure-cli installation method to support package increments
  provisioning/ubuntu-provision.sh
Labels: skip-changelog, skip-ci

#827 cleanup: remove tfsec
  provisioning/tools-versions.yml
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: cleanup, tfsec
