Repository jenkins-infra/packer-images, pull requests merged in 2023-02, with the labels that each got.

#474 chore(Jenkinsfile): ensure that Docker ARM64 Linux are published
  Jenkinsfile_k8s
Labels: chore

#510 chore(pipeline) fix deployment of the Linux Docker images to properly support multiple architectures
  Jenkinsfile_k8s
  provisioning/ubuntu-provision.sh
Labels: chore

#519 chore: add dependabot to ensure GitHub actions are tracked
  .github/workflows/dependabot.yml
Labels: chore

#520 fix(ubuntu) add `docker-buildx-plugin` package (orphaned from `docker-ce-cli` since Docker-CE 23.x)
  provisioning/ubuntu-provision.sh
Labels: bug

#452 feat(Windows-AWS) Switch from EC2 Launch v1 to v2 (support of both 2019 and 2022)
  build-jenkins-agent-windows.pkr.hcl
  datasources.pkr.hcl
  provisioning/EC2-LaunchConfig.json
  provisioning/windows-provision.ps1
Labels: enhancement, windows
