Repository jenkins-infra/packer-images, pull requests merged in 2024-12, with the labels that each got.

#1596 chore(GC/azure): fix Azure VM deletion by changing timeCreated to createdTime
  cleanup/azure.sh
Labels: skip-changelog

#1597 chore(GC/azure) remove debug
  cleanup/azure.sh
Labels: skip-changelog

#1602 feat(aws) use `gp3` EBS volume
  sources.pkr.hcl
Labels: enhancement

#1603 fix(ubuntu/windows) avoid tragedy of commons goods: use `dlcdn` apache download server for Maven
  provisioning/ubuntu-provision.sh
  provisioning/windows-provision.ps1
Labels: bug, windows, ubuntu, maven

#1611 feat(windows) add AWS EC2 builds (2019 and 2022)
  Jenkinsfile_k8s
  build-jenkins-agent-ubuntu.pkr.hcl
  build-jenkins-agent-windows.pkr.hcl
  images-versions.yaml
  install-packer.sh
  locals.pkr.hcl
  provisioning/windows-provision.ps1
  sources.pkr.hcl
  tests/goss-common.yaml
  tests/goss-linux.yaml
Labels: enhancement, windows, aws

#1585 Add install of .NET 3.5
  provisioning/windows-provision.ps1
  tests/goss-windows.yaml
Labels: enhancement, windows, dotnet

#1616 chore(tests): move hadolint to goss-common and add specific timeout
  build-jenkins-agent-windows.pkr.hcl
  tests/goss-common.yaml
  tests/goss-linux.yaml
  tests/goss-windows.yaml
Labels: chore
