Repository jenkins-infra/packer-images, pull requests merged in 2024-11, with the labels that each got.

#1512 Revert "Bump `ruby` version to 3.3.6"
  provisioning/tools-versions.yml
  tests/goss-linux.yaml
  tests/goss-windows.yaml
Labels: skip-changelog

#1514 chore(updatecli) when a new Ruby version is available, check for its existence in the ASDF Ruby plugin
  updatecli/updatecli.d/ruby.yml
Labels: chore, updatecli

#1508 chore(updatecli):Track docker image digests for `ubuntu 22_04 AMD64` and `ubuntu 22_04 ARM64`
  images-versions.yaml
  sources.pkr.hcl
  updatecli/updatecli.d/docker-ubuntu-22-04-amd64-images.yml
  updatecli/updatecli.d/docker-ubuntu-22-04-arm64-images.yml
Labels: chore, updatecli, ubuntu, docker

#1526 chore(jenkinsfile) adds garbage collector as distinct job for azure vms
  Jenkinsfile_gc
  cleanup/aws.sh
  cleanup/aws_images.sh
  cleanup/aws_snapshots.sh
Labels: skip-changelog

#1528 chore(`Jenkinsfile_k8s`) removes GC stage from pipeline
  Jenkinsfile_k8s
Labels: skip-changelog

#1527 chore(garbage-collector) adds aws gc stage to `jenkinsfile_gc` pipeline
  Jenkinsfile_gc
  cleanup/aws.sh
  cleanup/aws_images.sh
  cleanup/aws_snapshots.sh
Labels: skip-changelog

#1537 chore(`Jenkinsfile_gc`) updates the agent used to `jnlp-linux-arm64`
  Jenkinsfile_gc
Labels: skip-changelog

#1538 Revert "Bump jx-release-version version to 2.7.7"
  provisioning/tools-versions.yml
  tests/goss-common.yaml
Labels: skip-changelog

#1544 hotfix(aws-garbage-collector) enables debugging for `aws.sh` script
  cleanup/aws.sh
Labels: skip-changelog

#1553 chore(`packer-images`) adds `Name` tag with a value matching the GC filter
  sources.pkr.hcl
Labels: skip-changelog

#1507 chore(updatecli):Track `ubuntu 22_04 AMD64` AZ images
  build-jenkins-agent-ubuntu.pkr.hcl
  updatecli/updatecli.d/az-ubuntu-22-04-amd64-images.yml
Labels: chore, updatecli, ubuntu

#1557 feat(aws garbage collector) skips snapshots in use
  cleanup/aws_snapshots.sh
Labels: skip-changelog
