Repository jenkins-infra/packer-images, pull requests merged in 2024-01, with the labels that each got.

#971 chore(updatecli): add manifest for helm/helmfile/helmplugins/sops
  updatecli/updatecli.d/helm.yml
  updatecli/updatecli.d/helm_diff.yml
  updatecli/updatecli.d/helm_git.yml
  updatecli/updatecli.d/helm_secrets.yml
  updatecli/updatecli.d/helmfile.yml
  updatecli/updatecli.d/sops.yml
Labels: chore, helm, helm-diff, helm-git, helm-secrets, helmfile, sops

#970 feat(linux): add yamllint tool
  goss/goss-linux.yaml
  provisioning/ubuntu-provision.sh
Labels: enhancement, yamllint

#1004 hotfix(docker): add golang to path
  sources.pkr.hcl
Labels: bug, ubuntu, linux

#1014 Revert "Bump vagrant version to 2.4.1"
  goss/goss-windows.yaml
  provisioning/tools-versions.yml
Labels: bug

#982 chore(updatecli): add a manifest for golang
  updatecli/updatecli.d/golang.yml
Labels: chore, golang
