Repository jenkins-infra/packer-images, pull requests merged in 2025-01, with the labels that each got.

#1626 fix(ubuntu) ensure golang installation works with the default `jenkins` user `GOPATH`
  provisioning/ubuntu-provision.sh
Labels: bug, golang

#1649 fix(windows) ensure Git has autoCRLF enabled
  provisioning/windows-provision.ps1
Labels: bug, windows

#1651 tests: bypass Docker Compose version check
  tests/goss-common.yaml
  updatecli/updatecli.d/docker-compose.yml
Labels: skip-changelog

#1661 feat(windows/ec2) enable Fast Launch with default setup
  build-jenkins-agent-ubuntu.pkr.hcl
  build-jenkins-agent-windows.pkr.hcl
  locals.pkr.hcl
  sources.pkr.hcl
  variables.pkr.hcl
Labels: enhancement, windows, aws

#1676 hotfix: revert `aws` CLI to `2.22.35`
  provisioning/tools-versions.yml
  tests/goss-common.yaml
Labels: bug, awscli

#1695 chore(goss/windows): adding back a retry timeout only for windows goss
  build-jenkins-agent-windows.pkr.hcl
Labels: chore, windows, goss

#1696 chore(updatecli): track ami for AWS windows 2019/2022
  updatecli/updatecli.d/windows-2019-aws-images.yaml
  updatecli/updatecli.d/windows-2019-azure-images.yml
  updatecli/updatecli.d/windows-2022-aws-images.yaml
  updatecli/updatecli.d/windows-2022-azure-images.yml
Labels: chore, updatecli, windows

#1700 chore(publish): skip image/ami creation if not on production
  sources.pkr.hcl
Labels: chore

#1704 Revert "Bump aws `windows 2019 AMD64` AMI ID"
  images-versions.yaml
Labels: skip-ci

#1705 Revert "Bump ASDF version to 0.16.0"
  provisioning/tools-versions.yml
  tests/goss-linux.yaml
Labels: skip-ci
